# Generated by Django 5.0.7 on 2024-09-23 15:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='default_avatar_l48hpr', max_length=255, verbose_name='avatar'),
        ),
    ]
