# Generated by Django 5.0.7 on 2024-09-25 17:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dvex4uzyg/image/upload/fl_preserve_transparency/v1727104361/CulinaryHub/default_avatar_l48hpr.jpg', max_length=255, verbose_name='avatar'),
        ),
    ]
