# Generated by Django 5.0.7 on 2024-09-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_created_at_recipe_image_recipe_tag_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
