# Generated by Django 5.0.7 on 2024-09-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
