# Generated by Django 5.0.7 on 2024-09-25 17:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image_recipe'),
        ),
    ]
